name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to upload assets to (e.g. v1.0.0)'
        required: true
        default: ''

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Upload JS to Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          tag_name: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}
          files: heatmap-card.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
